#!/bin/bash


if [ $# -lt 1 ]; then
 echo "No source .csv file!"
 echo "Example:"
 echo " csv2sv in.csv"
 exit 1
fi


file=`basename $1 .csv`

cp $1 /tmp/$file.csv

pushd /tmp > /dev/null

sed -e "s/^\"//"            $file.csv > tmp0
sed -e "s/\"[,]*$//"        tmp0      > tmp1
sed -e "s/^[,]*$//"         tmp1      > tmp2

sed -ie "/^\/\//d"          tmp2

sed -ie "/CHIPSEL/s/\"//g"  tmp2
sed -ie "/ADR_BUS/s/\"//g"  tmp2
sed -ie "/RD_DATA/s/\"//g"  tmp2
sed -ie "/WR_DATA/s/\"//g"  tmp2
sed -ie "/WR_CTRL/s/\"//g"  tmp2
sed -ie "/RD_CTRL/s/\"//g"  tmp2
sed -ie "/CLK_SIG/s/\"//g"  tmp2
sed -ie "/RST_SIG/s/\"//g"  tmp2
sed -ie "/RDD_DLY/s/\"//g"  tmp2

sed -e "/^X/s/\"//g"       tmp2 > tmp3
sed -e "/^LOOP/s/\"//g"    tmp3 > tmp4
sed -e "/^ENDLOOP/s/\"//g" tmp4 > tmp5
sed -e "/^,\"/s/\"//g"     tmp5 > tmp6
sed -e "/,,,,\"/s/$/\"/"   tmp6 > $file.csv.cook

# back to invoke place
popd > /dev/null

echo ""
echo "CSV2RDF processing.."
csv2rdf.pl /tmp/$file.csv.cook $file.rdf.src

echo ""
echo "PPP     processing.."
ppp $file.rdf.src > $file.rdf

echo "File $file.rdf generated"

echo ""
echo "DOC2SV  processing.."
doc2sv.pl $file.rdf
